### ISSUE TITLE
How to run your demo？

### ISSUE THREAD

**Issue by xuguozhi** [faddey-w/face-swap#1]
plz tell us the steps to run your demo, thanks~

**Comment by xuguozhi** [comment]
here is the error message when run python3 demo.py:

> File "demo.py", line 5, in <module>
    from face_swap.data_lib import Dataset
  File "/home/xuguozhi/projects/deepfake/face-swap/face_swap/data_lib.py", line 13, in <module>
    from face_swap.config import Config
  File "/home/xuguozhi/projects/deepfake/face-swap/face_swap/config.py", line 5
    RANDOM_SEED: int
               ^
SyntaxError: invalid syntax

**Comment by faddey-w** [comment]
please make sure you run it with python 3.7. most probably you get a syntax error because of earlier version.

**Comment by xuguozhi** [comment]
> please make sure you run it with python 3.7. most probably you get a syntax error because of earlier version.

yes, I tried python 3.7, and everything works fine!
Thanks!
